name: Novius CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint-php:

    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add Nova key
        run: composer config http-basic.nova.laravel.com $LARAVEL_NOVA_USERNAME $LARAVEL_NOVA_LICENSE_KEY
        env:
          LARAVEL_NOVA_USERNAME: ${{ secrets.LARAVEL_NOVA_USERNAME }}
          LARAVEL_NOVA_LICENSE_KEY: ${{ secrets.LARAVEL_NOVA_LICENSE_KEY }}

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Lint PHP code via Laravel Pint
        run: composer run-script lint

  phpstan:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        operating-system: ['ubuntu-latest']
        php-versions: ['8.2', '8.3', '8.4']
        laravel: [ 11.*, 12.* ]
        nova: [ 4.*, 5.* ]
        dependency-version: [ prefer-stable ]
        include:
          - laravel: 12.*
            testbench: 10.*
            carbon: 3.*
          - laravel: 11.*
            testbench: 9.*
            carbon: 2.*
        exclude:
          - laravel: 12.*
            nova: 4.*

    name: phpstan - P${{ matrix.php-versions }} - L${{ matrix.laravel }} - N${{ matrix.nova }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add Nova key
        run: composer config http-basic.nova.laravel.com $LARAVEL_NOVA_USERNAME $LARAVEL_NOVA_LICENSE_KEY
        env:
          LARAVEL_NOVA_USERNAME: ${{ secrets.LARAVEL_NOVA_USERNAME }}
          LARAVEL_NOVA_LICENSE_KEY: ${{ secrets.LARAVEL_NOVA_LICENSE_KEY }}

      - name: Install Dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "nesbot/carbon:${{ matrix.carbon }}" "orchestra/testbench:${{ matrix.testbench }}" "laravel/nova:${{ matrix.nova }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: PHPStan Static Analysis
        run: composer run-script phpstan
